# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add_one": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/nbdev_bug/"

git_url = "https://github.com/fastai/nbdev_bug/tree/master/"

def custom_doc_links(name): return None
